# Включает поддержку конструкции import.meta.url
rules:
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  no-console: off
  import/extensions: off
env:
  browser: true
  commonjs: true
  es2021: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
